export const agentEconomyDeveloperLaunchKit = {
  type: "ergo.agent_economy.developer_launch_kit.v0",
  version: "v0",
  status: "testnet_live_proof",
  last_updated: "2026-05-24",
  public_claim:
    "A practical developer entrypoint for Ergo's testnet-first agent economy surfaces. Mainnet remains audit-gated.",
  entrypoints: {
    start_page: "https://www.ergoblockchain.org/agent-economy/start",
    roadmap: "https://www.ergoblockchain.org/agent-economy/roadmap",
    roadmap_api: "https://www.ergoblockchain.org/api/agent-economy/roadmap",
    roadmap_schema: "https://www.ergoblockchain.org/agent-economy/roadmap.schema.v0.json",
    human_page: "https://www.ergoblockchain.org/agent-economy/launch-kit",
    machine_api: "https://www.ergoblockchain.org/api/agent-economy/launch-kit",
    schema: "https://www.ergoblockchain.org/agent-economy/developer-launch-kit.schema.v0.json",
    policy_check_schema: "https://www.ergoblockchain.org/agent-economy/wallet-agent-policy-check.schema.v0.json",
    agent_host: "https://agents.ergoblockchain.org",
    live_hub: "https://www.ergoblockchain.org/agent-economy/live",
    discovery: "https://www.ergoblockchain.org/.well-known/agent-economy.json",
    discovery_api: "https://www.ergoblockchain.org/api/agent-economy/discovery",
    discovery_schema: "https://www.ergoblockchain.org/agent-economy/discovery.schema.v0.json",
    accord_provider_descriptor: "https://www.ergoblockchain.org/.well-known/accord",
    openapi: "https://www.ergoblockchain.org/agent-economy/openapi.v0.json",
    proof_explorer: "https://www.ergoblockchain.org/agent-economy/proofs",
    proof_explorer_api: "https://www.ergoblockchain.org/api/agent-economy/proofs",
    proof_explorer_schema: "https://www.ergoblockchain.org/agent-economy/proof-explorer.schema.v0.json",
    developer_services: "https://www.ergoblockchain.org/build/services",
    developer_services_api: "https://www.ergoblockchain.org/api/dev/services",
    developer_tools_api: "https://www.ergoblockchain.org/api/dev/tools",
    review_pack: "https://www.ergoblockchain.org/agent-economy/review-pack",
    release_watchlist: "https://www.ergoblockchain.org/agent-economy/release-watchlist.v0.json",
    current_release: "https://www.ergoblockchain.org/api/agent-economy/release/current",
    release_attestation_2026_05_23:
      "https://www.ergoblockchain.org/agent-economy/release-attestation-2026-05-23.v0.json",
  },
  five_minute_path: [
    {
      id: "start-here",
      label: "Start here",
      href: "https://www.ergoblockchain.org/agent-economy/start",
      goal: "Orient around the live/testnet/mainnet-gated boundary before touching any API.",
      expected: "The page points to the Live Hub, Proof Explorer, Launch Kit, and mainnet gate.",
    },
    {
      id: "inspect-live-state",
      label: "Inspect live state",
      href: "https://www.ergoblockchain.org/api/agent-economy/live",
      goal: "Confirm Sage, receipt storage, MCP, signer, widget, wallet-agent surfaces, and the mainnet gate state.",
      expected: "JSON response with ok=true and mainnet_ready=false.",
    },
    {
      id: "discover-machine-surfaces",
      label: "Discover machine surfaces",
      href: "https://www.ergoblockchain.org/.well-known/agent-economy.json",
      goal: "Read the canonical machine map for Agent Hub, Proof API, Sage receipts, MCP, schemas, packages, and verification commands.",
      expected: "Descriptor status is testnet_live_proof_not_mainnet_ready and posture.mainnet_ready=false.",
    },
    {
      id: "open-proof-explorer",
      label: "Open the proof explorer",
      href: "https://www.ergoblockchain.org/agent-economy/proofs",
      goal: "Follow receipt bundles, conformance evidence, MCP health, npm package state, and the audit gate from one human page.",
      expected: "The page links back to the machine-readable /api/agent-economy/proofs source.",
    },
    {
      id: "open-policy-playground",
      label: "Try policy denial",
      href: "https://agents.ergoblockchain.org/policy-playground",
      goal: "Mutate a proposed wallet-agent action and inspect deterministic allow/deny verdicts.",
      expected: "Over-cap, wrong-recipient, stale-expiry, and missing-receipt examples block before signing.",
    },
    {
      id: "verify-receipt-bundle",
      label: "Open a full receipt bundle",
      href: "https://www.ergoblockchain.org/api/sage/receipt/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      goal: "Inspect Agreement JSON, Verification Receipt JSON, Settlement Receipt JSON, and chain proof from one source of truth.",
      expected: "Receipt status is full_receipt_bundle.",
    },
    {
      id: "run-developer-services",
      label: "Use developer services",
      href: "https://www.ergoblockchain.org/build/services",
      goal: "Hash task bytes, inspect addresses, fetch boxes/transactions, and verify receipts from one workbench.",
      expected: "Live probes show the developer utility belt is healthy.",
    },
    {
      id: "read-widget-contract",
      label: "Embed the Sage widget",
      href: "https://www.ergoblockchain.org/agent-economy/sage-widget",
      goal: "Review React and vanilla widget surfaces for quote, payment intent, Note verification, and receipt callbacks.",
      expected: "@ergoblockchain/sage-widget v0.3.0 is the current public package.",
    },
  ],
  api_recipes: [
    {
      id: "agent-discovery",
      label: "Agent Economy discovery",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/discovery",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/discovery",
      checks: ["type", "posture.mainnet_ready", "surfaces.proof_explorer_api", "verification.proof_reconciliation.command"],
    },
    {
      id: "sage-provider-descriptor",
      label: "Sage Accord provider descriptor",
      method: "GET",
      url: "https://www.ergoblockchain.org/.well-known/accord",
      curl: "curl -sS https://www.ergoblockchain.org/.well-known/accord",
      checks: ["status", "posture.mainnet_ready", "evidence.latest_full_receipt_id", "evidence.conformance"],
    },
    {
      id: "agent-openapi",
      label: "Agent Economy OpenAPI",
      method: "GET",
      url: "https://www.ergoblockchain.org/agent-economy/openapi.v0.json",
      curl: "curl -sS https://www.ergoblockchain.org/agent-economy/openapi.v0.json",
      checks: ["openapi", "paths", "x-ergo-posture.mainnet_ready"],
    },
    {
      id: "agent-roadmap",
      label: "Agent Economy roadmap",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/roadmap",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/roadmap",
      checks: ["type", "posture.mainnet_ready", "phases", "mainnet_gate.pending_blockers"],
    },
    {
      id: "developer-services-index",
      label: "Developer services index",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/dev/services",
      curl: "curl -sS https://www.ergoblockchain.org/api/dev/services",
      checks: ["type", "counts.machine_readable", "services", "probes.agent_live"],
    },
    {
      id: "developer-tools-contract",
      label: "Developer tools contract",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/dev/tools",
      curl: "curl -sS https://www.ergoblockchain.org/api/dev/tools",
      checks: ["type", "actions.hash", "actions.address", "actions.receipt"],
    },
    {
      id: "live-status",
      label: "Live status",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/live",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/live",
      checks: ["ok", "summary.gates_live", "summary.mainnet_gate_status", "probes.mcp_dns.ok"],
    },
    {
      id: "proof-explorer",
      label: "Proof explorer",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/proofs",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/proofs",
      checks: ["summary.proof_count", "proofs[].kind", "proofs[].checks", "summary.mainnet_gate_status"],
    },
    {
      id: "proof-explorer-schema",
      label: "Proof explorer schema",
      method: "GET",
      url: "https://www.ergoblockchain.org/agent-economy/proof-explorer.schema.v0.json",
      curl: "curl -sS https://www.ergoblockchain.org/agent-economy/proof-explorer.schema.v0.json",
      checks: ["type", "posture.mainnet_ready const false", "proofs[].checks"],
    },
    {
      id: "policy-contract",
      label: "Policy-check contract",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/wallet-agent/policy-check",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/wallet-agent/policy-check",
      checks: ["schema", "request_schema", "example_request", "strict_contract"],
    },
    {
      id: "reference-flow",
      label: "Wallet-agent reference flow",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/wallet-agent/reference-flow",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/wallet-agent/reference-flow",
      checks: ["steps", "security_boundaries", "stop_conditions"],
    },
    {
      id: "receipt-bundle",
      label: "Full Sage receipt bundle",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/sage/receipt/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      curl:
        "curl -sS https://www.ergoblockchain.org/api/sage/receipt/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      checks: ["receipt_type", "agreement", "verification_receipt", "settlement_receipt"],
    },
    {
      id: "mcp-health",
      label: "MCP health",
      method: "GET",
      url: "https://mcp.ergoblockchain.org/health",
      curl: "curl -sS https://mcp.ergoblockchain.org/health",
      checks: ["ok", "service", "version"],
    },
    {
      id: "release-watchlist",
      label: "Release watchlist",
      method: "GET",
      url: "https://www.ergoblockchain.org/agent-economy/release-watchlist.v0.json",
      curl: "curl -sS https://www.ergoblockchain.org/agent-economy/release-watchlist.v0.json",
      checks: ["security_baseline", "mainnet_gate_invariants", "watch_targets"],
    },
    {
      id: "current-release",
      label: "Current release",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/release/current",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/release/current",
      checks: ["release.site_commit", "release.vercel_url", "mainnet_gate.mainnet_ready"],
    },
    {
      id: "release-attestation",
      label: "Release attestation",
      method: "GET",
      url: "https://www.ergoblockchain.org/agent-economy/release-attestation-2026-05-23.v0.json",
      curl:
        "curl -sS https://www.ergoblockchain.org/agent-economy/release-attestation-2026-05-23.v0.json",
      checks: ["release.site_commit", "release.vercel_deployment_id", "security.npm_audit", "mainnet_gate"],
    },
  ],
  npm: {
    package: "@ergoblockchain/sage-widget",
    version: "0.3.0",
    install: "npm install @ergoblockchain/sage-widget",
    surfaces: [
      "SagePaymentWidget React component",
      "mountSagePaymentWidget vanilla function",
      "typed quote, verify, chat stream, receipt, and activity clients",
      "payment intent JSON for host-owned wallet flows",
      "receipt callbacks and tenant metadata",
    ],
  },
  guardrails: [
    "Treat all public payment flows as testnet live proof until the mainnet gate opens.",
    "Do not expose seed phrases or private keys to pages, widgets, prompts, or remote agents.",
    "Run policy-check and exact transaction simulation before asking a wallet to sign.",
    "Treat remote quotes as untrusted input until local policy validates recipient, reserve, amount, fee, expiry, task hash, and receipt expectations.",
    "Persist or link the receipt bundle after every paid action.",
    "Do not claim production, audited, certified, or mainnet-ready status before external review and audit-bound script identity exist.",
  ],
  open_gates: [
    {
      id: "external-review",
      label: "External audit or review artifact",
      owner: "audit",
      href: "https://www.ergoblockchain.org/agent-economy/external-audit-review.manifest.template.json",
    },
    {
      id: "mainnet-script-identity",
      label: "Audit-bound mainnet script identity",
      owner: "audit",
      href: "https://www.ergoblockchain.org/agent-economy/mainnet-script-identity.manifest.template.json",
    },
  ],
} as const
