export const agentEconomyDeveloperLaunchKit = {
  type: "ergo.agent_economy.developer_launch_kit.v0",
  version: "v0",
  status: "testnet_live_proof",
  last_updated: "2026-05-22",
  public_claim:
    "A practical developer entrypoint for Ergo's testnet-first agent economy surfaces. Mainnet remains audit-gated.",
  entrypoints: {
    human_page: "https://www.ergoblockchain.org/agent-economy/launch-kit",
    machine_api: "https://www.ergoblockchain.org/api/agent-economy/launch-kit",
    schema: "https://www.ergoblockchain.org/agent-economy/developer-launch-kit.schema.v0.json",
    policy_check_schema: "https://www.ergoblockchain.org/agent-economy/wallet-agent-policy-check.schema.v0.json",
    agent_host: "https://agents.ergoblockchain.org",
    live_hub: "https://www.ergoblockchain.org/agent-economy/live",
    developer_services: "https://www.ergoblockchain.org/build/services",
    review_pack: "https://www.ergoblockchain.org/agent-economy/review-pack",
  },
  five_minute_path: [
    {
      id: "inspect-live-state",
      label: "Inspect live state",
      href: "https://www.ergoblockchain.org/api/agent-economy/live",
      goal: "Confirm Sage, receipt storage, MCP, signer, widget, wallet-agent surfaces, and the mainnet gate state.",
      expected: "JSON response with ok=true and mainnet_ready=false.",
    },
    {
      id: "open-policy-playground",
      label: "Try policy denial",
      href: "https://agents.ergoblockchain.org/policy-playground",
      goal: "Mutate a proposed wallet-agent action and inspect deterministic allow/deny verdicts.",
      expected: "Over-cap, wrong-recipient, stale-expiry, and missing-receipt examples block before signing.",
    },
    {
      id: "verify-receipt-bundle",
      label: "Open a full receipt bundle",
      href: "https://www.ergoblockchain.org/api/sage/receipt/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      goal: "Inspect Agreement JSON, Verification Receipt JSON, Settlement Receipt JSON, and chain proof from one source of truth.",
      expected: "Receipt status is full_receipt_bundle.",
    },
    {
      id: "run-developer-services",
      label: "Use developer services",
      href: "https://www.ergoblockchain.org/build/services",
      goal: "Hash task bytes, inspect addresses, fetch boxes/transactions, and verify receipts from one workbench.",
      expected: "Live probes show the developer utility belt is healthy.",
    },
    {
      id: "read-widget-contract",
      label: "Embed the Sage widget",
      href: "https://www.ergoblockchain.org/agent-economy/sage-widget",
      goal: "Review React and vanilla widget surfaces for quote, payment intent, Note verification, and receipt callbacks.",
      expected: "@ergoblockchain/sage-widget v0.3.0 is the current public package.",
    },
  ],
  api_recipes: [
    {
      id: "live-status",
      label: "Live status",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/live",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/live",
      checks: ["ok", "summary.gates_live", "summary.mainnet_gate_status", "probes.mcp_dns.ok"],
    },
    {
      id: "policy-contract",
      label: "Policy-check contract",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/wallet-agent/policy-check",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/wallet-agent/policy-check",
      checks: ["schema", "request_schema", "example_request", "strict_contract"],
    },
    {
      id: "reference-flow",
      label: "Wallet-agent reference flow",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/wallet-agent/reference-flow",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/wallet-agent/reference-flow",
      checks: ["steps", "security_boundaries", "stop_conditions"],
    },
    {
      id: "receipt-bundle",
      label: "Full Sage receipt bundle",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/sage/receipt/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      curl:
        "curl -sS https://www.ergoblockchain.org/api/sage/receipt/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      checks: ["receipt_type", "agreement", "verification_receipt", "settlement_receipt"],
    },
    {
      id: "mcp-health",
      label: "MCP health",
      method: "GET",
      url: "https://mcp.ergoblockchain.org/health",
      curl: "curl -sS https://mcp.ergoblockchain.org/health",
      checks: ["ok", "service", "version"],
    },
  ],
  npm: {
    package: "@ergoblockchain/sage-widget",
    version: "0.3.0",
    install: "npm install @ergoblockchain/sage-widget",
    surfaces: [
      "SagePaymentWidget React component",
      "mountSagePaymentWidget vanilla function",
      "typed quote, verify, chat stream, receipt, and activity clients",
      "payment intent JSON for host-owned wallet flows",
      "receipt callbacks and tenant metadata",
    ],
  },
  guardrails: [
    "Treat all public payment flows as testnet live proof until the mainnet gate opens.",
    "Do not expose seed phrases or private keys to pages, widgets, prompts, or remote agents.",
    "Run policy-check and exact transaction simulation before asking a wallet to sign.",
    "Treat remote quotes as untrusted input until local policy validates recipient, reserve, amount, fee, expiry, task hash, and receipt expectations.",
    "Persist or link the receipt bundle after every paid action.",
    "Do not claim production, audited, certified, or mainnet-ready status before external review and audit-bound script identity exist.",
  ],
  open_gates: [
    {
      id: "external-review",
      label: "External audit or review artifact",
      owner: "audit",
      href: "https://www.ergoblockchain.org/agent-economy/external-audit-review.manifest.template.json",
    },
    {
      id: "mainnet-script-identity",
      label: "Audit-bound mainnet script identity",
      owner: "audit",
      href: "https://www.ergoblockchain.org/agent-economy/mainnet-script-identity.manifest.template.json",
    },
  ],
} as const
