export const agentEconomyDeveloperLaunchKit = {
  type: "ergo.agent_economy.developer_launch_kit.v0",
  version: "v0",
  status: "testnet_live_proof",
  last_updated: "2026-05-26",
  public_claim:
    "A practical developer entrypoint for Ergo's testnet-first agent economy surfaces. Mainnet remains audit-gated.",
  entrypoints: {
    start_page: "https://www.ergoblockchain.org/agent-economy/start",
    roadmap: "https://www.ergoblockchain.org/agent-economy/roadmap",
    roadmap_api: "https://www.ergoblockchain.org/api/agent-economy/roadmap",
    roadmap_schema: "https://www.ergoblockchain.org/agent-economy/roadmap.schema.v0.json",
    human_page: "https://www.ergoblockchain.org/agent-economy/launch-kit",
    machine_api: "https://www.ergoblockchain.org/api/agent-economy/launch-kit",
    schema: "https://www.ergoblockchain.org/agent-economy/developer-launch-kit.schema.v0.json",
    first_receipt: "https://www.ergoblockchain.org/agent-economy/first-receipt",
    first_receipt_api: "https://www.ergoblockchain.org/api/agent-economy/first-receipt",
    first_receipt_schema: "https://www.ergoblockchain.org/agent-economy/first-receipt-flow.schema.v0.json",
    policy_check_schema: "https://www.ergoblockchain.org/agent-economy/wallet-agent-policy-check.schema.v0.json",
    agent_host: "https://agents.ergoblockchain.org",
    live_hub: "https://www.ergoblockchain.org/agent-economy/live",
    discovery: "https://www.ergoblockchain.org/.well-known/agent-economy.json",
    discovery_api: "https://www.ergoblockchain.org/api/agent-economy/discovery",
    discovery_schema: "https://www.ergoblockchain.org/agent-economy/discovery.schema.v0.json",
    accord_provider_descriptor: "https://www.ergoblockchain.org/.well-known/accord",
    openapi: "https://www.ergoblockchain.org/agent-economy/openapi.v0.json",
    proof_explorer: "https://www.ergoblockchain.org/agent-economy/proofs",
    proof_explorer_api: "https://www.ergoblockchain.org/api/agent-economy/proofs",
    proof_explorer_schema: "https://www.ergoblockchain.org/agent-economy/proof-explorer.schema.v0.json",
    developer_services: "https://www.ergoblockchain.org/build/services",
    developer_services_api: "https://www.ergoblockchain.org/api/dev/services",
    developer_tools_api: "https://www.ergoblockchain.org/api/dev/tools",
    review_pack: "https://www.ergoblockchain.org/agent-economy/review-pack",
    release_watchlist: "https://www.ergoblockchain.org/agent-economy/release-watchlist.v0.json",
    current_release: "https://www.ergoblockchain.org/api/agent-economy/release/current",
    release_attestation_2026_05_23:
      "https://www.ergoblockchain.org/agent-economy/release-attestation-2026-05-23.v0.json",
  },
  five_minute_path: [
    {
      id: "check-live-state",
      label: "Check live state",
      href: "https://www.ergoblockchain.org/api/agent-economy/live",
      goal: "Confirm the stack is live on testnet and mainnet readiness is still closed.",
      expected: "ok=true, latest_full_receipt_id is present, and mainnet_ready=false.",
    },
    {
      id: "open-latest-receipt",
      label: "Open latest receipt",
      href: "https://www.ergoblockchain.org/r/sage/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      goal: "See the human-readable proof object before reading any implementation detail.",
      expected: "Agreement, verification, settlement, and chain proof resolve from one receipt.",
    },
    {
      id: "inspect-receipt-json",
      label: "Inspect receipt JSON",
      href: "https://www.ergoblockchain.org/api/sage/receipt/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      goal: "Read the machine contract: Agreement JSON, Verification Receipt JSON, Settlement Receipt JSON, and chain proof.",
      expected: "receipt_type=full_receipt_bundle and status=settled_on_chain.",
    },
    {
      id: "run-policy-check",
      label: "Run policy check",
      href: "https://agents.ergoblockchain.org/policy-playground",
      goal: "Change a proposed wallet-agent action and watch local policy block unsafe requests before signing.",
      expected: "Over-cap, wrong-recipient, stale-expiry, and missing-receipt examples are denied.",
    },
    {
      id: "build-same-flow",
      label: "Build same flow",
      href: "https://www.ergoblockchain.org/build/agent-payments/quickstart",
      goal: "Use the Sage widget package to request a quote, create a payment intent, verify a Note, and fetch a receipt.",
      expected: "The quickstart keeps wallet authority host-owned and receipt callbacks explicit.",
    },
    {
      id: "read-mainnet-gate",
      label: "Read mainnet gate",
      href: "https://www.ergoblockchain.org/agent-economy/trust",
      goal: "Confirm what is not claimed before taking the pattern toward real funds or production custody.",
      expected: "Mainnet remains closed until external review and audit-bound script identity exist.",
    },
  ],
  api_recipes: [
    {
      id: "first-receipt-flow",
      label: "Build first receipt flow",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/first-receipt",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/first-receipt",
      checks: ["type", "outcome.latest_full_receipt_id", "steps", "policy_check.example_verdict.allowed", "mainnet_ready"],
    },
    {
      id: "agent-discovery",
      label: "Agent Economy discovery",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/discovery",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/discovery",
      checks: ["type", "posture.mainnet_ready", "surfaces.proof_explorer_api", "verification.proof_reconciliation.command"],
    },
    {
      id: "sage-provider-descriptor",
      label: "Sage Accord provider descriptor",
      method: "GET",
      url: "https://www.ergoblockchain.org/.well-known/accord",
      curl: "curl -sS https://www.ergoblockchain.org/.well-known/accord",
      checks: ["status", "posture.mainnet_ready", "evidence.latest_full_receipt_id", "evidence.conformance"],
    },
    {
      id: "agent-openapi",
      label: "Agent Economy OpenAPI",
      method: "GET",
      url: "https://www.ergoblockchain.org/agent-economy/openapi.v0.json",
      curl: "curl -sS https://www.ergoblockchain.org/agent-economy/openapi.v0.json",
      checks: ["openapi", "paths", "x-ergo-posture.mainnet_ready"],
    },
    {
      id: "agent-roadmap",
      label: "Agent Economy roadmap",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/roadmap",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/roadmap",
      checks: ["type", "posture.mainnet_ready", "phases", "mainnet_gate.pending_blockers"],
    },
    {
      id: "developer-services-index",
      label: "Developer services index",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/dev/services",
      curl: "curl -sS https://www.ergoblockchain.org/api/dev/services",
      checks: ["type", "counts.machine_readable", "services", "probes.agent_live"],
    },
    {
      id: "developer-tools-contract",
      label: "Developer tools contract",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/dev/tools",
      curl: "curl -sS https://www.ergoblockchain.org/api/dev/tools",
      checks: ["type", "actions.hash", "actions.address", "actions.receipt"],
    },
    {
      id: "live-status",
      label: "Live status",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/live",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/live",
      checks: ["ok", "summary.gates_live", "summary.mainnet_gate_status", "probes.mcp_dns.ok"],
    },
    {
      id: "proof-explorer",
      label: "Proof explorer",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/proofs",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/proofs",
      checks: ["summary.proof_count", "proofs[].kind", "proofs[].checks", "summary.mainnet_gate_status"],
    },
    {
      id: "proof-explorer-schema",
      label: "Proof explorer schema",
      method: "GET",
      url: "https://www.ergoblockchain.org/agent-economy/proof-explorer.schema.v0.json",
      curl: "curl -sS https://www.ergoblockchain.org/agent-economy/proof-explorer.schema.v0.json",
      checks: ["type", "posture.mainnet_ready const false", "proofs[].checks"],
    },
    {
      id: "policy-contract",
      label: "Policy-check contract",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/wallet-agent/policy-check",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/wallet-agent/policy-check",
      checks: ["schema", "request_schema", "example_request", "strict_contract"],
    },
    {
      id: "reference-flow",
      label: "Wallet-agent reference flow",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/wallet-agent/reference-flow",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/wallet-agent/reference-flow",
      checks: ["steps", "security_boundaries", "stop_conditions"],
    },
    {
      id: "receipt-bundle",
      label: "Full Sage receipt bundle",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/sage/receipt/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      curl:
        "curl -sS https://www.ergoblockchain.org/api/sage/receipt/f8752d10a2ece92fbc88065c3b92b94da621ec65943098f43c9e084deb763d81",
      checks: ["receipt_type", "agreement", "verification_receipt", "settlement_receipt"],
    },
    {
      id: "mcp-health",
      label: "MCP health",
      method: "GET",
      url: "https://mcp.ergoblockchain.org/health",
      curl: "curl -sS https://mcp.ergoblockchain.org/health",
      checks: ["ok", "service", "version"],
    },
    {
      id: "release-watchlist",
      label: "Release watchlist",
      method: "GET",
      url: "https://www.ergoblockchain.org/agent-economy/release-watchlist.v0.json",
      curl: "curl -sS https://www.ergoblockchain.org/agent-economy/release-watchlist.v0.json",
      checks: ["security_baseline", "mainnet_gate_invariants", "watch_targets"],
    },
    {
      id: "current-release",
      label: "Current release",
      method: "GET",
      url: "https://www.ergoblockchain.org/api/agent-economy/release/current",
      curl: "curl -sS https://www.ergoblockchain.org/api/agent-economy/release/current",
      checks: ["release.site_commit", "release.vercel_url", "mainnet_gate.mainnet_ready"],
    },
    {
      id: "release-attestation",
      label: "Release attestation",
      method: "GET",
      url: "https://www.ergoblockchain.org/agent-economy/release-attestation-2026-05-23.v0.json",
      curl:
        "curl -sS https://www.ergoblockchain.org/agent-economy/release-attestation-2026-05-23.v0.json",
      checks: ["release.site_commit", "release.vercel_deployment_id", "security.npm_audit", "mainnet_gate"],
    },
  ],
  npm: {
    package: "@ergoblockchain/sage-widget",
    version: "0.3.0",
    install: "npm install @ergoblockchain/sage-widget",
    surfaces: [
      "SagePaymentWidget React component",
      "mountSagePaymentWidget vanilla function",
      "typed quote, verify, chat stream, receipt, and activity clients",
      "payment intent JSON for host-owned wallet flows",
      "receipt callbacks and tenant metadata",
    ],
  },
  guardrails: [
    "Treat all public payment flows as testnet live proof until the mainnet gate opens.",
    "Do not expose seed phrases or private keys to pages, widgets, prompts, or remote agents.",
    "Run policy-check and exact transaction simulation before asking a wallet to sign.",
    "Treat remote quotes as untrusted input until local policy validates recipient, reserve, amount, fee, expiry, task hash, and receipt expectations.",
    "Persist or link the receipt bundle after every paid action.",
    "Do not claim production, audited, certified, or mainnet-ready status before external review and audit-bound script identity exist.",
  ],
  open_gates: [
    {
      id: "external-review",
      label: "External audit or review artifact",
      owner: "audit",
      href: "https://www.ergoblockchain.org/agent-economy/external-audit-review.manifest.template.json",
    },
    {
      id: "mainnet-script-identity",
      label: "Audit-bound mainnet script identity",
      owner: "audit",
      href: "https://www.ergoblockchain.org/agent-economy/mainnet-script-identity.manifest.template.json",
    },
  ],
} as const
