import { latestFullReceiptId } from "./agent-discovery"
import { agentMarketPosture } from "./agent-market"

const BASE_URL = "https://www.ergoblockchain.org"
const MCP_URL = "https://mcp.ergoblockchain.org"

export const economicMcpLastReviewed = "2026-05-28"

export const economicMcpManifest = {
  type: "ergo.economic_mcp_tools.v0",
  version: "v0",
  status: "safe_runtime_tools_prepared",
  last_reviewed: economicMcpLastReviewed,
  canonical: `${BASE_URL}/api/agents/mcp-tools`,
  human: `${BASE_URL}/agents/mcp`,
  schema: `${BASE_URL}/agent-economy/economic-mcp-tools.schema.v0.json`,
  mcp: {
    health: `${MCP_URL}/health`,
    streamable_http: `${MCP_URL}/mcp`,
    repository: "https://github.com/bez111/ergoblockchain-mcp",
    prepared_version: "0.3.0",
  },
  posture: agentMarketPosture,
  public_claim:
    "Economic MCP tool contracts for the Ergo Agent Economy. The manifest is published; runtime MCP tools should prepare intents and proofs, not sign transactions or custody value.",
  runtime_boundary: {
    mcp_tools_sign_transactions: false,
    mcp_tools_hold_private_keys: false,
    mcp_tools_broadcast_without_wallet_boundary: false,
    mcp_tools_override_wallet_policy: false,
    mainnet_ready: false,
    production_custody: false,
  },
  recommended_client_flow: [
    "discover services",
    "query receipt-derived reputation",
    "list jobs",
    "request or scaffold quote",
    "create Agreement draft",
    "check wallet policy",
    "hand unsigned or reduced transaction to a host wallet boundary",
    "verify receipt bundle after work",
    "query mainnet gate before making claims",
  ],
  counts: {
    tools_total: 14,
    http_backed_today: 10,
    mcp_runtime_tools_prepared: 11,
    mcp_runtime_tools_deployed: 0,
    signing_tools_allowed: 0,
    mainnet_ready_tools: 0,
  },
  tools: [
    {
      name: "ergo_discover_services",
      status: "http_backed_runtime_prepared",
      purpose: "Find provider, verifier, broker, reserve, reputation, and tool endpoint entries without scraping pages.",
      input_schema: "none",
      output_schema: `${BASE_URL}/agent-economy/agent-service-registry.schema.v0.json`,
      http_endpoint: `${BASE_URL}/api/agents/registry`,
      safe_use: "Read-only discovery.",
    },
    {
      name: "ergo_publish_service",
      status: "http_backed_runtime_prepared",
      purpose: "Validate a provider manifest and return the operator-review submit draft before registry inclusion.",
      input_schema: `${BASE_URL}/agent-economy/agent-service-registry.schema.v0.json#/$defs/service`,
      output_schema: `${BASE_URL}/agent-economy/agent-service-publish.schema.v0.json`,
      http_endpoint: `${BASE_URL}/api/agents/publish`,
      safe_use: "Validation and submit-draft only; does not publish registry entries, sign transactions, custody value, or open mainnet claims.",
    },
    {
      name: "ergo_list_jobs",
      status: "http_backed_runtime_prepared",
      purpose: "List receipt-backed bootstrap jobs that agents can inspect and request assignment for.",
      input_schema: "none",
      output_schema: `${BASE_URL}/agent-economy/agent-jobs.schema.v0.json`,
      http_endpoint: `${BASE_URL}/api/jobs`,
      safe_use: "Read-only discovery of testnet work opportunities.",
    },
    {
      name: "ergo_accept_job",
      status: "http_backed_runtime_prepared",
      purpose: "Validate a worker-agent acceptance intent before any operator assigns work.",
      input_schema: `${BASE_URL}/agent-economy/agent-job-acceptance.schema.v0.json`,
      output_schema: `${BASE_URL}/agent-economy/agent-job-acceptance.schema.v0.json`,
      http_endpoint: `${BASE_URL}/api/jobs/accept`,
      safe_use: "Validation only; does not assign, escrow, pay, or settle.",
    },
    {
      name: "ergo_get_quote",
      status: "http_backed_runtime_prepared",
      purpose: "Create a job-bound quote scaffold with Agreement draft and receipt expectation.",
      input_schema: `${BASE_URL}/agent-economy/agent-job-quote.schema.v0.json`,
      output_schema: `${BASE_URL}/agent-economy/agent-job-quote.schema.v0.json`,
      http_endpoint: `${BASE_URL}/api/jobs/quote`,
      safe_use: "Scaffold only; requires operator approval before any wallet action.",
    },
    {
      name: "ergo_create_agreement",
      status: "local_runtime_scaffold_prepared",
      purpose: "Turn an accepted quote into an Agreement draft that binds task, price, deadline, receipt expectation, and settlement boundary.",
      input_schema: `${BASE_URL}/agent-economy/agent-job-quote.schema.v0.json`,
      output_schema: `${BASE_URL}/api/sage/receipt/${latestFullReceiptId}`,
      http_endpoint: `${BASE_URL}/api/jobs/quote`,
      safe_use: "Draft only; not a signed contract and not a mainnet claim.",
    },
    {
      name: "ergo_check_policy",
      status: "http_backed_runtime_prepared",
      purpose: "Check whether a proposed agent wallet action is allowed, denied, or requires human approval.",
      input_schema: `${BASE_URL}/agent-economy/wallet-agent-policy-check.schema.v0.json`,
      output_schema: `${BASE_URL}/agent-economy/wallet-agent-policy-check.schema.v0.json`,
      http_endpoint: `${BASE_URL}/api/agent-economy/wallet-agent/policy-check`,
      safe_use: "Policy verdict only; never signs, broadcasts, or holds wallet authority.",
    },
    {
      name: "ergo_create_payment_intent",
      status: "local_runtime_scaffold_prepared",
      purpose: "Prepare a host-wallet payment intent for an agent action after quote and policy checks.",
      input_schema: `${BASE_URL}/agent-economy/wallet-agent-policy-check.schema.v0.json`,
      output_schema: `${BASE_URL}/agent-economy/wallet-agent-reference-flow.v0.json`,
      http_endpoint: `${BASE_URL}/api/agent-economy/wallet-agent/reference-flow`,
      safe_use: "Intent only; signing remains inside ErgoConnect, ErgoPay, or another host wallet boundary.",
    },
    {
      name: "ergo_verify_note",
      status: "sage_provider_specific",
      purpose: "Verify a Sage testnet Note payment against the quote and task hash.",
      input_schema: "Sage verify-payment request",
      output_schema: `${BASE_URL}/api/sage/receipt/${latestFullReceiptId}`,
      http_endpoint: `${BASE_URL}/api/sage/verify-payment`,
      safe_use: "Provider-specific testnet verification; not a generic mainnet verifier.",
    },
    {
      name: "ergo_submit_work",
      status: "planned",
      purpose: "Submit provider output with task-hash binding and receipt expectation after assignment.",
      input_schema: "provider output manifest",
      output_schema: "verification receipt draft",
      http_endpoint: null,
      safe_use: "Future provider-side flow; no automatic settlement.",
    },
    {
      name: "ergo_issue_receipt",
      status: "planned",
      purpose: "Issue or store Agreement, Verification Receipt, and Settlement Receipt JSON for a completed flow.",
      input_schema: "receipt bundle draft",
      output_schema: `${BASE_URL}/api/sage/receipt/${latestFullReceiptId}`,
      http_endpoint: null,
      safe_use: "Future receipt-storage flow; receipt API remains source of truth.",
    },
    {
      name: "ergo_verify_receipt",
      status: "http_backed_runtime_prepared",
      purpose: "Inspect a receipt bundle and verify agreement, verification, settlement, hashes, and chain proof consistency.",
      input_schema: "receipt_id",
      output_schema: `${BASE_URL}/api/sage/receipt/${latestFullReceiptId}`,
      http_endpoint: `${BASE_URL}/api/sage/receipt/{id}`,
      safe_use: "Read-only verification; old receipts may remain chain-proof-only.",
    },
    {
      name: "ergo_redeem_note",
      status: "guarded_runtime_boundary_prepared",
      purpose: "Redeem a Note after policy, signer ops, and settlement constraints are satisfied.",
      input_schema: "operator-controlled signer request",
      output_schema: "settlement receipt",
      http_endpoint: null,
      safe_use: "Not exposed as a public MCP tool. Redemption belongs behind signer ops, limits, and wallet boundaries.",
    },
    {
      name: "ergo_query_reputation",
      status: "http_backed_runtime_prepared",
      purpose: "Query receipt-derived reputation subjects, evidence links, verifier coverage, disputes, and trust boundaries.",
      input_schema: "none",
      output_schema: `${BASE_URL}/agent-economy/agent-reputation.schema.v0.json`,
      http_endpoint: `${BASE_URL}/api/agents/reputation`,
      safe_use: "Not a centralized rating, certification, or mainnet readiness score.",
    },
  ],
  forbidden_assumptions: [
    "Do not claim MCP tools can sign transactions.",
    "Do not claim MCP tools hold wallet keys or custody value.",
    "Do not claim prepared MCP 0.3 tools are deployed until mcp.ergoblockchain.org advertises them.",
    "Do not claim mainnet readiness, audit certification, or production custody from this manifest.",
    "Do not bypass ErgoConnect, ErgoPay, host wallet prompts, or wallet-agent policy checks.",
  ],
  next_steps: [
    "Deploy ergoblockchain-mcp 0.3.0 after the final batch is ready.",
    "Smoke /mcp tools/list and update mcp_runtime_tools_deployed only after production advertises the prepared tools.",
    "Keep intent-preparation tools non-signing and wallet-policy-bound.",
    "Keep redemption outside public MCP until signer ops, limits, and external review are stronger.",
  ],
} as const

export type EconomicMcpManifest = typeof economicMcpManifest
