import type { Metadata } from "next"
import "./globals.css"
import { siteConfig } from "@/config/site-config";
import { GoogleAnalytics } from "@/components/analytics/google-analytics";
import { SEOMonitor } from "@/components/seo/seo-monitor";
import { Suspense } from "react";
import { createOrganizationSchema, createWebSiteSchema } from "@/lib/seo";
import { renderSchemaScripts } from "@/components/seo/SEOSchemas";

/* ISR: статическая генерация + обновление каждые 5 минут */
export const revalidate = 300;

const rootTitle = "Ergo — Public Proof Surface for Autonomous Work";
const rootDescription =
  "Ergo is a PoW/eUTXO clearing layer and public proof surface for autonomous work: programmable acceptance, receipt bundles, wallet policy, and audit-gated settlement.";

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.siteUrl),
  title: {
    default: rootTitle,
    template: "%s | Ergo Platform"
  },
  description: rootDescription,
  keywords: [
    "ergo blockchain",
    "Ergo",
    "ERG",
    "ERG coin",
    "ERG wallet",
    "buy ERG",
    "PoW blockchain",
    "autonomous work settlement",
    "public proof surface",
    "verifiable receipts",
    "agent economy",
    "autonomous work clearing",
    "agent settlement receipts",
    "programmable credit",
    "task-conditioned settlement",
    "AI agent payments",
    "agentic blockchain",
    "blockchain for AI agents",
    "autonomous AI payments blockchain",
    "machine-to-machine payments",
    "smart contracts",
    "DeFi platform",
    "UTXO DeFi",
    "ErgoScript",
    "Sigma Protocols",
    "Autolykos",
    "GPU mining",
    "ASIC resistant mining",
    "Babel Fees",
    "Storage Rent",
    "NiPoPoWs",
    "Oracle Pools",
    "native tokens",
    "ErgoMixer",
    "SigmaUSD",
    "Rosen Bridge",
    "Spectrum Finance",
    "eUTXO model",
    "proof of work",
    "censorship resistant money",
    "sound money",
    "fair launch cryptocurrency",
    "no premine",
    "cypherpunk blockchain",
    "MEV resistance",
    "cryptocurrency",
    "blockchain development",
    "decentralized finance",
    "privacy blockchain",
    "autonomous agent settlement",
    "autonomous agent payments",
    "ergo agent economy",
  ],
  authors: [{ name: "Ergo Platform" }],
  creator: "Ergo Platform",
  publisher: "Ergo Platform",
  // Explicit icon graph. Files are regenerated by scripts/build-icons.mjs
  // from public/icon.svg so they always match the brand mark used in the
  // header. Modern browsers (Firefox, Chrome, Safari) prefer the SVG; the
  // multi-size .ico covers older clients; apple-touch-icon is what
  // WhatsApp / iOS / many share-preview crawlers fall back to when no
  // OpenGraph image is present.
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/favicon.ico", sizes: "16x16 32x32 48x48" },
      { url: "/icon-192x192.png", type: "image/png", sizes: "192x192" },
      { url: "/icon-512x512.png", type: "image/png", sizes: "512x512" },
    ],
    shortcut: "/favicon.ico",
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteConfig.siteUrl,
    siteName: 'Ergo Platform',
    title: rootTitle,
    description: rootDescription,
    images: [
      {
        // Absolute URLs — Telegram and several other share-preview
        // crawlers ignore relative paths even with metadataBase set.
        url: `${siteConfig.siteUrl}/og-image.png`,
        secureUrl: `${siteConfig.siteUrl}/og-image.png`,
        width: 1200,
        height: 630,
        alt: 'Ergo — Public Proof Surface for Autonomous Work',
        type: 'image/png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: rootTitle,
    description: rootDescription,
    images: [`${siteConfig.siteUrl}/og-image.png`],
    creator: siteConfig.twitterHandle,
  },
  alternates: {
    canonical: siteConfig.siteUrl,
    languages: {
      'en': 'https://www.ergoblockchain.org',
      'ru': 'https://www.ergoblockchain.org/ru',
      'fr': 'https://www.ergoblockchain.org/fr',
      'de': 'https://www.ergoblockchain.org/de',
      'es': 'https://www.ergoblockchain.org/es',
      'zh-CN': 'https://www.ergoblockchain.org/zh-cn',
      'zh-TW': 'https://www.ergoblockchain.org/zh-tw',
      'tr': 'https://www.ergoblockchain.org/tr',
      'pt-BR': 'https://www.ergoblockchain.org/pt-br',
      'it': 'https://www.ergoblockchain.org/it',
      'ja': 'https://www.ergoblockchain.org/ja',
      'ko-KR': 'https://www.ergoblockchain.org/ko-kr',
    },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // TODO: добавить реальные коды верификации Google Search Console и Yandex Webmaster
  // verification: {
  //   google: 'YOUR_REAL_GOOGLE_CODE',
  //   yandex: 'YOUR_REAL_YANDEX_CODE',
  // },
  // Icons auto-generated by Next.js from src/app/icon.png and src/app/apple-icon.png
}

// Site-wide JSON-LD via centralized SEO module. Keep this as one script so
// Next/head processing never sees adjacent JSON documents as one payload.
const siteSchemaGraph = {
  "@context": "https://schema.org",
  "@graph": [createOrganizationSchema(), createWebSiteSchema()],
}

const seoMonitorEnabled = process.env.NEXT_PUBLIC_SEO_MONITOR === "true"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      dir="ltr"
      suppressHydrationWarning
    >
      <head>
        {/* Preconnect to third-party origins used in critical render path */}
        <link rel="preconnect" href="https://www.googletagmanager.com" crossOrigin="" />
        <link rel="preconnect" href="https://www.google-analytics.com" crossOrigin="" />
        <link rel="preconnect" href="https://vitals.vercel-insights.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://www.ergoblockchain.org" />
        {/* OpenSearch — lets browsers add Ergo site search to their search bar */}
        <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Ergo Platform" />
        {renderSchemaScripts([siteSchemaGraph])}
      </head>
      <body className="min-h-screen bg-background font-sans antialiased" suppressHydrationWarning>
        <Suspense>
          <GoogleAnalytics />
        </Suspense>
        {seoMonitorEnabled ? <SEOMonitor enabled debug={process.env.NODE_ENV === 'development'} /> : null}
        {children}
      </body>
    </html>
  );
}
