import { NextResponse } from 'next/server'
import { generateMultilingualSitemap, sitemapHeaders, filterIndexablePages } from '@/lib/sitemap-utils'

export async function GET() {
  const staticPages = [
    { url: '/', priority: 1.0, changefreq: 'daily' as const },
    { url: '/use', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/miners', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/hodlers', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/developers', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/technology', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/technology/privacy-features', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/ergoscript', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/eutxo-model', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/nipopows', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/storage-rent', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/oracle-pools', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/native-tokens', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/secure-pow', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/babel-fees', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/subblocks', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/velvet-forks', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/technology/adaptive-emission', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/ecosystem', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/ergo-watch', priority: 0.8, changefreq: 'daily' as const },
    { url: '/ergo-watch/agents', priority: 0.8, changefreq: 'hourly' as const },
    { url: '/blog', priority: 0.9, changefreq: 'daily' as const },
    { url: '/learn', priority: 0.7, changefreq: 'weekly' as const },
    { url: '/learn/glossary', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/start', priority: 0.7, changefreq: 'weekly' as const },
    { url: '/start/introduction', priority: 0.6, changefreq: 'monthly' as const },
    { url: '/docs', priority: 0.6, changefreq: 'weekly' as const },
    { url: '/wallet', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/start/community', priority: 0.7, changefreq: 'monthly' as const },
    { url: '/start/comparison', priority: 0.7, changefreq: 'monthly' as const },
    { url: '/faq', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/ecosystem/grants', priority: 0.7, changefreq: 'weekly' as const },
    { url: '/ecosystem/map', priority: 0.7, changefreq: 'weekly' as const },
    { url: '/learn/ergoscript', priority: 0.7, changefreq: 'monthly' as const },
    { url: '/learn/research', priority: 0.7, changefreq: 'monthly' as const },
    { url: '/compare', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/playbooks', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/patterns', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/infographics', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/questions', priority: 0.9, changefreq: 'daily' as const },
    { url: '/topics', priority: 0.9, changefreq: 'daily' as const },
    { url: '/agents', priority: 0.95, changefreq: 'weekly' as const },
    { url: '/agents/registry', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/agents/publish', priority: 0.85, changefreq: 'weekly' as const },
    { url: '/jobs', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/build/ergo-connect', priority: 0.85, changefreq: 'weekly' as const },
    // Agent Economy & Build
    { url: '/agent-economy', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/agent-economy/start', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/agent-economy/clearing', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/agent-economy/interop', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/agent-economy/live', priority: 0.9, changefreq: 'hourly' as const },
    { url: '/agent-economy/first-receipt', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/agent-economy/launch-kit', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/agent-economy/proofs', priority: 0.9, changefreq: 'hourly' as const },
    { url: '/agent-economy/roadmap', priority: 0.9, changefreq: 'weekly' as const },
    { url: '/agent-economy/metrics', priority: 0.8, changefreq: 'hourly' as const },
    { url: '/agent-economy/trust', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/agent-economy/review-pack', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/agent-economy/wallet-agent', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/agent-economy/sage-widget', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/agent-economy/manifesto', priority: 0.8, changefreq: 'monthly' as const },
    { url: '/agent-economy/vs', priority: 0.8, changefreq: 'monthly' as const },
    { url: '/demos', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/demos/x402-accord-gateway', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/demos/mcp-paid-tool', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/demos/agent-api-payment', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/demos/agent-credit-note', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/build', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/build/agent-payments', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/build/agent-payments/quickstart', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/build/agent-payments/policy-playground', priority: 0.7, changefreq: 'weekly' as const },
    { url: '/build/agent-payments/wallet-agent-runner', priority: 0.7, changefreq: 'weekly' as const },
    { url: '/build/quickstart', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/build/playground', priority: 0.8, changefreq: 'weekly' as const },
    { url: '/build/services', priority: 0.8, changefreq: 'weekly' as const },
    // Agent registry
    { url: '/ergo-watch/agents/submit', priority: 0.7, changefreq: 'monthly' as const },
    // Press + annual report
    { url: '/press', priority: 0.6, changefreq: 'monthly' as const },
    { url: '/state-of-ergo-2026', priority: 0.9, changefreq: 'monthly' as const },
    // Legal
    { url: '/legal/privacy', priority: 0.4, changefreq: 'yearly' as const },
    { url: '/legal/terms', priority: 0.4, changefreq: 'yearly' as const },
    { url: '/legal/risk', priority: 0.5, changefreq: 'yearly' as const },
    { url: '/legal/security', priority: 0.4, changefreq: 'yearly' as const },
  ]

  const sitemap = generateMultilingualSitemap(filterIndexablePages(staticPages))

  return new NextResponse(sitemap, { headers: sitemapHeaders })
}
