"use client";

/* eslint-disable react/no-unescaped-entities */

import React from "react";
import Link from "next/link";
import { CodeBlock } from "@/components/ui";

export default function Eip0005Page() {
  return (
    <>
      <h1 className="text-4xl font-bold bg-gradient-to-r from-orange-400 to-cyan-400 bg-clip-text text-transparent mb-4 leading-tight pb-1">
        EIP-0005: Contract Template Documentation
      </h1>
      <Link
        href="/docs/developers/infrastructure/wallets/standards"
        className="inline-flex items-center px-6 py-3 bg-orange-500 rounded-xl font-semibold text-black hover:bg-orange-600 transition-transform hover:scale-105 mb-8"
      >
        Back to Standards
      </Link>
      <div className="text-gray-400 text-sm mb-6">
        <div><b>Author:</b> aslesarenko</div>
        <div><b>Status:</b> Proposed</div>
        <div><b>Created:</b> 06-Apr-2020</div>
        <div><b>License:</b> CC0</div>
        <div><b>Forking:</b> Not Needed</div>
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-8">Overview</h2>
      <p className="text-gray-300 mb-4">
        EIP-0005 outlines a standard for serializing contract templates and including metadata to make them reusable across multiple platforms. It aims to provide a way for developers to easily move contract templates between different protocol implementations, applications, and tools.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">Background And Motivation</h2>
      <p className="text-gray-300 mb-4">
        Ergo employs a robust language, known as <a href="https://ergoplatform.org/docs/ErgoTree.pdf" className="text-blue-400 hover:underline" target="_blank" rel="noopener noreferrer">ErgoTree</a>, to create guarding propositions that protect UTXO boxes. While ErgoTree's serialization is efficient for storage and transaction validation, it lacks the metadata necessary for broader application use. This EIP aims to extend ErgoTree's capabilities by adding serialization formats for contract templates, including metadata for more versatile applications.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">Example Use Cases</h2>
      <ul className="list-disc pl-6 text-gray-300 mb-4">
        <li>ErgoTree compilers can generate contract templates complete with necessary metadata.</li>
        <li>Contract templates generated by one compiler (e.g., ErgoScala) can be used in environments where specific libraries (e.g., Java jar generated by Scala2.12) are not supported.</li>
        <li>The contract template becomes a self-contained entity, making it easier to store, transfer, parse, or execute across different platforms and tools.</li>
      </ul>

      <h2 className="text-2xl font-bold mb-4 mt-8">Contract Template Serialization Format</h2>
      <p className="text-gray-300 mb-4">
        This section provides the binary serialization format for contract templates, optimized for compact storage and wire transfer. Below is a table illustrating the fields and their formats:
      </p>
      <div className="overflow-x-auto mb-6">
        <table className="min-w-[600px] w-full text-sm text-left border border-neutral-700 rounded-xl">
          <thead>
            <tr className="bg-neutral-900 text-cyan-300">
              <th className="py-2 px-3 font-bold">Field Name</th>
              <th className="py-2 px-3 font-bold">Format</th>
              <th className="py-2 px-3 font-bold">Example</th>
              <th className="py-2 px-3 font-bold">Description</th>
            </tr>
          </thead>
          <tbody className="text-gray-300">
            <tr><td className="py-2 px-3">TreeVersion</td><td className="py-2 px-3">Opt[UByte]</td><td className="py-2 px-3">1</td><td className="py-2 px-3">Optional version of ErgoTree to be used</td></tr>
            <tr><td className="py-2 px-3">NameLength</td><td className="py-2 px-3">VLQ(UInt)</td><td className="py-2 px-3">18</td><td className="py-2 px-3">Length of Name in bytes</td></tr>
            <tr><td className="py-2 px-3">Name</td><td className="py-2 px-3">Bytes</td><td className="py-2 px-3">"rewardOutputScript"</td><td className="py-2 px-3">User-readable name of the contract</td></tr>
            <tr><td className="py-2 px-3">DescLength</td><td className="py-2 px-3">VLQ(UInt)</td><td className="py-2 px-3">20</td><td className="py-2 px-3">Length of Description in bytes</td></tr>
            <tr><td className="py-2 px-3">Description</td><td className="py-2 px-3">Bytes</td><td className="py-2 px-3">"holds mining rewards"</td><td className="py-2 px-3">User-readable contract description</td></tr>
            <tr><td className="py-2 px-3">...</td><td className="py-2 px-3">...</td><td className="py-2 px-3">...</td><td className="py-2 px-3">...</td></tr>
          </tbody>
        </table>
      </div>
      <p className="text-gray-400 text-sm mb-4">See the original EIP-0005 document for complete field descriptions and further details.</p>

      <h2 className="text-2xl font-bold mb-4 mt-8">Parameter Serialization Format</h2>
      <div className="overflow-x-auto mb-6">
        <table className="min-w-[600px] w-full text-sm text-left border border-neutral-700 rounded-xl">
          <thead>
            <tr className="bg-neutral-900 text-cyan-300">
              <th className="py-2 px-3 font-bold">Field Name</th>
              <th className="py-2 px-3 font-bold">Format</th>
              <th className="py-2 px-3 font-bold">Example</th>
              <th className="py-2 px-3 font-bold">Description</th>
            </tr>
          </thead>
          <tbody className="text-gray-300">
            <tr><td className="py-2 px-3">NameLength</td><td className="py-2 px-3">VLQ(UInt)</td><td className="py-2 px-3">7</td><td className="py-2 px-3">Length of Name in bytes</td></tr>
            <tr><td className="py-2 px-3">Name</td><td className="py-2 px-3">Bytes</td><td className="py-2 px-3">"minerPk"</td><td className="py-2 px-3">User-readable parameter name</td></tr>
            <tr><td className="py-2 px-3">DescLength</td><td className="py-2 px-3">VLQ(UInt)</td><td className="py-2 px-3">18</td><td className="py-2 px-3">Length of Description in bytes</td></tr>
            <tr><td className="py-2 px-3">Description</td><td className="py-2 px-3">Bytes</td><td className="py-2 px-3">"miner's public key"</td><td className="py-2 px-3">User-readable parameter description</td></tr>
            <tr><td className="py-2 px-3">ConstantIndex</td><td className="py-2 px-3">VLQ(UInt)</td><td className="py-2 px-3">1</td><td className="py-2 px-3">Index in the ErgoTree.constants array</td></tr>
          </tbody>
        </table>
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-8">JSON Format</h2>
      <p className="text-gray-300 mb-4">
        Contract templates can also be serialized into JSON format, suitable for applications that require human-readable or editable templates. A sample JSON representation is as follows:
      </p>
      <CodeBlock language="typescript">{`{
  "name": "rewardOutputScript",
  "description": "holds mining rewards",
  ...
}`}</CodeBlock>

      <h2 className="text-2xl font-bold mb-4 mt-8">Conversion to ErgoTree</h2>
      <p className="text-gray-300 mb-4">
        This section outlines how to convert a contract template into an ErgoTree structure. The conversion allows for the substitution of new values for the constants in the template, either redefining the default values or providing missing ones.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">Notes on Supporting this EIP in ErgoTree Compilers</h2>
      <p className="text-gray-300 mb-4">
        Compilers like ErgoScript and ErgoScala can easily incorporate this EIP by generating templates packaged as either JSON or bytes. Annotations in the source code can also aid the compiler in generating the appropriate metadata and serialization formats.
      </p>

      <hr className="my-8 border-neutral-700" />
      <p className="text-gray-400 mb-4">
        For complete technical details and field specifications, refer to the original <a href="https://github.com/ergoplatform/eips/blob/master/eip-0005.md" className="text-blue-400 hover:underline" target="_blank" rel="noopener noreferrer">EIP-0005 document</a>.
      </p>
    </>
  );
} 