"use client";

import React from "react";
import Link from "next/link";
import { 
  ChevronRight, Shield, Key, Lock, Unlock, 
  Settings, ExternalLink, FileText, AlertCircle,
  CheckCircle, ArrowRight, Wallet
} from "lucide-react";

export default function WalletSetupPage() {
  return (
    <>
      <h1 className="text-4xl font-bold bg-gradient-to-r from-orange-400 to-cyan-400 bg-clip-text text-transparent mb-6 leading-tight pb-1">
        Ergo Wallet Setup and Security
      </h1>

      <div className="mb-8">
        <Link
          href="/Docs/developers/infrastructure/node/configuration"
          className="inline-flex items-center px-5 py-2 bg-orange-500 rounded-lg font-semibold text-black hover:bg-orange-600 transition hover:scale-[1.02]"
        >
          <ChevronRight className="w-5 h-5 mr-2" /> Back to Node Configuration
        </Link>
      </div>

      <div className="space-y-8">
        {/* Overview Section */}
        <section className="bg-orange-400/10 border border-orange-400/20 rounded-xl p-6">
          <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
            <Shield className="w-6 h-6 text-orange-400" /> Wallet Overview
          </h2>
          <p className="text-gray-300 text-lg leading-relaxed">
            The Ergo node includes a built-in wallet function to securely store your private keys and sign transactions. 
            The wallet utilizes the BIP-39 standard to generate a master seed from a mnemonic sentence (seed phrase). 
            This seed is then used to derive private keys according to the BIP-32 standard for Hierarchical Deterministic (HD) Wallets.
          </p>
          <div className="mt-4 bg-neutral-800/50 border border-neutral-700 rounded-lg p-4">
            <p className="text-gray-300 text-sm">
              While you <em>can</em> compose your own mnemonic sentence using words from the provided{' '}
              <a href="https://github.com/ergoplatform/ergo-wallet/tree/master/src/main/resources/wordlist" 
                 className="text-cyan-400 hover:underline">
                wordlists
              </a>, it is strongly recommended for security to use a mnemonic generated by a trusted source 
              (like the node itself or a secure hardware wallet).
            </p>
            <p className="text-gray-300 text-sm mt-3">
              The length of the mnemonic sentence determines the security level (entropy): 12, 15, 18, 21, or 24 words 
              correspond to 128, 160, 192, 224, or 256 bits of security, respectively. To restore a wallet from an 
              existing mnemonic, use the <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">/wallet/restore</code> API endpoint.
            </p>
            <p className="text-gray-300 text-sm mt-3">
              All wallet interactions with the node are performed through its REST API. Before proceeding, ensure you have{' '}
              <Link href="/Docs/developers/infrastructure/node/configuration#rest-api-settings" 
                    className="text-cyan-400 hover:underline">
                set an API key hash
              </Link> in your node's configuration file to protect sensitive API calls.
            </p>
          </div>
        </section>

        {/* Configuration Section */}
        <section>
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            <Settings className="w-6 h-6 text-green-400" /> Configuring the Wallet
          </h2>
          <div className="bg-neutral-900/50 border border-neutral-700 rounded-xl p-6">
            <p className="text-gray-300 mb-4">
              Wallet-related settings are managed in the <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">ergo.wallet</code> section 
              of the node configuration file. Key parameters include:
            </p>
            <div className="grid md:grid-cols-1 gap-4">
              <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4">
                <h4 className="font-bold text-green-400 mb-2">seedStrengthBits</h4>
                <p className="text-gray-300 text-sm">Specifies the bit-length (entropy) for newly generated seeds. A higher value results in a longer, more secure mnemonic phrase. Options: <code className="bg-neutral-800 px-1 py-0.5 rounded text-cyan-400">128, 160, 192, 224, 256</code>. Default is usually 128.</p>
              </div>
              <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
                <h4 className="font-bold text-blue-400 mb-2">secretStorage.secretDir</h4>
                <p className="text-gray-300 text-sm">Defines the directory where the encrypted wallet file (<code className="bg-neutral-800 px-1 py-0.5 rounded text-cyan-400">wallet.dat</code>) will be stored.</p>
              </div>
              <div className="bg-purple-500/10 border border-purple-500/20 rounded-lg p-4">
                <h4 className="font-bold text-purple-400 mb-2">mnemonicPhraseLanguage</h4>
                <p className="text-gray-300 text-sm">Sets the language for generating or restoring mnemonic phrases. Options: <code className="bg-neutral-800 px-1 py-0.5 rounded text-cyan-400">"chinese_simplified", "chinese_traditional", "english", "french", "italian", "japanese", "korean", "spanish"</code>. Default is "english".</p>
              </div>
            </div>
          </div>
        </section>

        {/* Initialization Section */}
        <section>
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            <Key className="w-6 h-6 text-yellow-400" /> Initializing the Wallet for the First Time
          </h2>
          <div className="bg-neutral-900/50 border border-neutral-700 rounded-xl p-6">
            <p className="text-gray-300 mb-4">
              When running a node for the first time, you initialize its wallet via the REST API using one of two methods:
            </p>
            
            <div className="grid md:grid-cols-2 gap-4 mb-6">
              <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4">
                <h4 className="font-bold text-green-400 mb-2">1. Initialize a New Wallet</h4>
                <p className="text-gray-300 text-sm mb-3">The node generates a new seed phrase for you.</p>
                <div className="space-y-2 text-xs">
                  <div><strong>Endpoint:</strong> <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">POST /wallet/init</code></div>
                  <div><strong>Request Body:</strong> <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">&#123;"pass": "YOUR_WALLET_PASSWORD", "mnemonicPass": "OPTIONAL_PASSPHRASE"&#125;</code></div>
                </div>
              </div>
              <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
                <h4 className="font-bold text-blue-400 mb-2">2. Restore from Existing Mnemonic</h4>
                <p className="text-gray-300 text-sm mb-3">Use a previously generated mnemonic phrase.</p>
                <div className="space-y-2 text-xs">
                  <div><strong>Endpoint:</strong> <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">POST /wallet/restore</code></div>
                  <div><strong>Request Body:</strong> <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">&#123;"pass": "YOUR_WALLET_PASSWORD", "mnemonic": "word1 word2 word3 ...", "mnemonicPass": "OPTIONAL_PASSPHRASE"&#125;</code></div>
                </div>
              </div>
            </div>

            <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <AlertCircle className="w-5 h-5 text-yellow-400" />
                <span className="font-semibold text-yellow-400">Important</span>
              </div>
              <p className="text-gray-300 text-sm">
                The response will contain the newly generated mnemonic phrase – <strong>save this phrase securely and offline immediately!</strong> 
                The <code className="bg-neutral-800 px-1 py-0.5 rounded text-cyan-400">mnemonicPass</code> (BIP-39 passphrase) is optional and adds an extra layer of security to the seed derivation.
              </p>
            </div>
          </div>
        </section>

        {/* Unlocking Section */}
        <section>
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            <Unlock className="w-6 h-6 text-green-400" /> Unlocking the Wallet
          </h2>
          <div className="bg-neutral-900/50 border border-neutral-700 rounded-xl p-6">
            <p className="text-gray-300 mb-4">
              After initialization or restoration, and after every node restart, the wallet must be unlocked before use. 
              To unlock it, make a POST request to <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">/wallet/unlock</code> with your wallet password: 
              <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">&#123;"pass": "YOUR_WALLET_PASSWORD"&#125;</code>.
            </p>
            <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <CheckCircle className="w-5 h-5 text-green-400" />
                <span className="font-semibold text-green-400">Required Operations</span>
              </div>
              <p className="text-gray-300 text-sm mb-2">The wallet must be unlocked to perform operations such as:</p>
              <ul className="space-y-1 text-gray-300 text-sm">
                <li className="flex items-center gap-2">
                  <span className="w-2 h-2 bg-green-400 rounded-full"></span>
                  Using the internal miner
                </li>
                <li className="flex items-center gap-2">
                  <span className="w-2 h-2 bg-green-400 rounded-full"></span>
                  Signing transactions
                </li>
                <li className="flex items-center gap-2">
                  <span className="w-2 h-2 bg-green-400 rounded-full"></span>
                  Tracking boxes
                </li>
              </ul>
            </div>
          </div>
        </section>

        {/* Locking Section */}
        <section>
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            <Lock className="w-6 h-6 text-red-400" /> Locking the Wallet
          </h2>
          <div className="bg-neutral-900/50 border border-neutral-700 rounded-xl p-6">
            <p className="text-gray-300 mb-4">
              The wallet typically locks automatically after a period of inactivity or upon node shutdown, flushing secrets from memory. 
              You can also lock it manually by making a GET request to <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">/wallet/lock</code>. 
              Locking the wallet when not actively using it is recommended for security.
            </p>
            <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <AlertCircle className="w-5 h-5 text-red-400" />
                <span className="font-semibold text-red-400">Security Note</span>
              </div>
              <p className="text-gray-300 text-sm">
                You will need to unlock it again before performing further operations after locking.
              </p>
            </div>
          </div>
        </section>

        {/* Managing Keys Section */}
        <section>
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            <Wallet className="w-6 h-6 text-purple-400" /> Managing Keys
          </h2>
          <div className="bg-neutral-900/50 border border-neutral-700 rounded-xl p-6">
            <p className="text-gray-300 mb-4">
              The wallet implements BIP-32, enabling the creation of hierarchical deterministic wallets. During initialization, 
              the master key is derived from the seed. To derive additional keys (and their corresponding addresses) based on 
              specific derivation paths (e.g., following EIP-3 standard paths like <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">m/44'/429'/0'/0/0</code>), 
              use the <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">POST /wallet/deriveKey</code> endpoint with the desired path in the request body: 
              <code className="bg-neutral-800 px-2 py-1 rounded text-cyan-400">&#123;"derivationPath": "m/44'/429'/0'/0/0"&#125;</code>.
            </p>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-purple-500/10 border border-purple-500/20 rounded-lg p-4">
                <h4 className="font-bold text-purple-400 mb-2">Specific Derivation Path</h4>
                <p className="text-gray-300 text-sm">Use <code className="bg-neutral-800 px-1 py-0.5 rounded text-cyan-400">POST /wallet/deriveKey</code> with a specific derivation path to generate keys following standards like EIP-3.</p>
              </div>
              <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
                <h4 className="font-bold text-blue-400 mb-2">Next Available Key</h4>
                <p className="text-gray-300 text-sm">Use <code className="bg-neutral-800 px-1 py-0.5 rounded text-cyan-400">GET /wallet/deriveNextKey</code> to derive the next available key in the sequence according to the wallet's internal counter.</p>
              </div>
            </div>
            <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4 mt-4">
              <div className="flex items-center gap-2 mb-2">
                <ExternalLink className="w-5 h-5 text-blue-400" />
                <span className="font-semibold text-blue-400">API Access</span>
              </div>
              <p className="text-gray-300 text-sm">
                All these wallet operations are performed via the Ergo node's REST API, typically accessed 
                through the Swagger UI or programmatically.
              </p>
            </div>
          </div>
        </section>

        {/* Security Warning */}
        <section className="bg-red-500/10 border border-red-500/20 rounded-xl p-6">
          <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
            <AlertCircle className="w-6 h-6 text-red-400" /> Security Best Practices
          </h2>
          <p className="text-gray-300 mb-4">
            Follow these security practices to protect your wallet and private keys:
          </p>
          <div className="bg-neutral-800/50 border border-neutral-700 rounded-lg p-4">
            <h4 className="font-bold text-red-400 mb-2">⚠️ Critical Security Notes:</h4>
            <ul className="space-y-2 text-gray-300 text-sm">
              <li className="flex items-center gap-2">
                <span className="w-2 h-2 bg-red-400 rounded-full"></span>
                Store mnemonic phrases securely offline
              </li>
              <li className="flex items-center gap-2">
                <span className="w-2 h-2 bg-red-400 rounded-full"></span>
                Never share your mnemonic or passphrase
              </li>
              <li className="flex items-center gap-2">
                <span className="w-2 h-2 bg-red-400 rounded-full"></span>
                Use strong passwords for wallet encryption
              </li>
              <li className="flex items-center gap-2">
                <span className="w-2 h-2 bg-red-400 rounded-full"></span>
                Consider using BIP-39 passphrase for extra security
              </li>
              <li className="flex items-center gap-2">
                <span className="w-2 h-2 bg-red-400 rounded-full"></span>
                Lock wallet when not in use
              </li>
              <li className="flex items-center gap-2">
                <span className="w-2 h-2 bg-red-400 rounded-full"></span>
                Set API key hash in configuration for sensitive operations
              </li>
            </ul>
          </div>
        </section>

        {/* Quick Links */}
        <section className="bg-neutral-900/50 border border-neutral-700 rounded-xl p-6">
          <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
            <ExternalLink className="w-6 h-6 text-orange-400" /> Quick Links
          </h2>
          <div className="grid md:grid-cols-2 gap-4">
            <Link
              href="/Docs/developers/infrastructure/node/configuration/wallet/initialize"
              className="flex items-center p-4 bg-orange-500/10 border border-orange-500/20 rounded-lg hover:bg-orange-500/20 transition-colors"
            >
              <Wallet className="w-5 h-5 mr-3 text-orange-400" />
              <div>
                <h4 className="font-semibold text-orange-400">Initialize Wallet</h4>
                <p className="text-gray-300 text-sm">Learn how to initialize and restore wallets</p>
              </div>
            </Link>
            <Link
              href="/Docs/developers/infrastructure/node/configuration/wallet/hierarchical"
              className="flex items-center p-4 bg-blue-500/10 border border-blue-500/20 rounded-lg hover:bg-blue-500/20 transition-colors"
            >
              <Key className="w-5 h-5 mr-3 text-blue-400" />
              <div>
                <h4 className="font-semibold text-blue-400">Hierarchical Keys</h4>
                <p className="text-gray-300 text-sm">Understand BIP-44 and EIP-3 standards</p>
              </div>
            </Link>
          </div>
        </section>
      </div>
    </>
  )
} 