import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { CodeBlock } from "@/components/ui";

export default function MosaikSimpleUIPage() {
  return (
    <>
      <h1 className="text-4xl font-bold bg-gradient-to-r from-orange-400 to-cyan-400 bg-clip-text text-transparent mb-6 leading-tight pb-1">Ergo Mosaik: A UI system for Ergo dApps</h1>
      <div className="mb-6">
        <Link
          href="/Docs/developers/tooling/pathways/mosaik/tutorial"
          className="inline-flex items-center px-5 py-2 bg-cyan-500 rounded-xl font-semibold text-black hover:bg-cyan-600 transition-transform hover:scale-105"
        >
          <ArrowLeft className="w-5 h-5 mr-2" />
          Back
        </Link>
      </div>
      <h2 className="text-2xl font-bold text-cyan-400 mb-4 mt-8">2: Building a simple UI with Mosaik Kotlin DSL and Spring Boot</h2>
      <p className="text-gray-300 mb-4">In Part 1 of this tutorial series for Ergo Mosaik, we have seen that Ergo Mosaik is a UI layer for dApps using Ergo. It is not the exclusive UI layer but aims to streamline the development process for dApp developers by providing a way to implement both off-chain code and UI code on the same tech stack. Additionally, some wallet applications ship with a built-in Mosaik executor so that your dApp UI can be used within these wallet applications.</p>
      <p className="text-gray-300 mb-4">Mosaik apps are a JSON-based markup language and can be generated by the tech stack of your choice. A reference implementation is provided by the Ergo core team to be used from Kotlin/JVM.</p>
      <p className="text-gray-300 mb-4">This choice was made because Kotlin/JVM can utilize the full functionality of ergo-appkit, Ergo’s first-hand SDK, and all libraries in the Java ecosystem, as well as providing a well-balanced mix of imperative and functional programming. Kotlin can process domain-specific languages and self-defined DSLs. This feature was used to give a <i>Mosaik DSL</i> with which the Mosaik user interface can be described naturally.</p>
      <p className="text-gray-300 mb-4">Because Kotlin/JVM seamlessly interoperates with the Java ecosystem, we can use Spring Boot to serve our Mosaik app to its executors. Spring Boot is a Java framework for building web services - REST APIs and dynamic websites - battle-tested, feature-rich and well-documented. You don’t need to use it when creating a Mosaik app, but we use it here in our examples because it helps implement REST APIs with very clean code.</p>
      <p className="text-gray-300 mb-4">So, let’s hop onto coding. You’ll need Java 11 installed on your system (open-source version preferred), and we recommend IntelliJ as the development environment, but you are free to use something else.</p>

      <h3 className="text-xl font-bold text-orange-400 mb-2 mt-8">Setting up a Spring Boot project</h3>
      <p className="text-gray-300 mb-4">To set up a Spring Boot project, visit the Spring Initializr on <a href="https://start.spring.io/" className="text-cyan-400 hover:underline" target="_blank" rel="noopener noreferrer">start.spring.io</a>. Change project to “Gradle project”, language to “Kotlin”, “Java” to “11”, and set the names as you want.</p>
      <p className="text-gray-300 mb-4">As dependencies, choose “Spring Web”.</p>
      <p className="text-gray-300 mb-4">You should end up with something like this:</p>
      <img src="../../../assets/img/mosaik/tutorial2-1.png" alt="Spring Initializr" className="rounded-xl border border-neutral-700 mb-6" />
      <p className="text-gray-300 mb-4">Generate the project, extract the zip file and open the directory with the IDE of your choice. Using IntelliJ or another Gradle-compatible IDE will sync some time to download and index all dependencies.</p>
      <p className="text-gray-300 mb-4">To start the Spring Boot application, you can use the Terminal command</p>
      <CodeBlock language="python">{`@RestController

class MosaikAppController {
   @GetMapping("/")
   fun getMainPage(): String {
       return "Hello"
   }
}`}</CodeBlock>
      <p className="text-gray-300 mb-4">If you start the server again and visit localhost:8080 in your web browser, you will see that “Hello” is printed. That’s even more success.</p>
      <p className="text-gray-300 mb-4">What did we do to achieve this?</p>
      <ul className="list-disc pl-6 text-gray-300 mb-4 space-y-1">
        <li>The <code>@RestController</code> annotation on the new class tells Spring that this class should be instantiated as a singleton, and its methods are designed for Rest APIs.</li>
        <li>Adding a method alone won’t do the trick, though: the API endpoint must be defined. That’s why the method itself has another annotation, which defines this method should be called when a GET request to path “/” comes in.</li>
        <li>Returned objects of the REST API methods are automatically serialized to JSON by Spring. In this case, we return a String for which the serialization is profane. Data classes work as well, and we will use this soon.</li>
      </ul>

      <h3 className="text-xl font-bold text-orange-400 mb-2 mt-8">Adding Mosaik to the project</h3>
      <p className="text-gray-300 mb-4">After making sure that Spring Boot is working, we now have to add Mosaik to the app. In the JVM ecosystem, libraries are served by Nexus servers, and the build tool fetches these libraries and adds them to the project during the build. We use Gradle as our build tool, and the dependencies for our project are declared in the <b>build.gradle.kts</b> file. Open it. You will find the following section:</p>
      <CodeBlock language="typescript">{`dependencies {

  implementation("org.springframework.boot:spring-boot-starter-web")
  implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
  implementation("org.jetbrains.kotlin:kotlin-reflect")
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
}`}</CodeBlock>
      <p className="text-gray-300 mb-4">So at the moment, spring boot web and some Kotlin extensions are declared. We add mosaik below the existing entries:</p>
      <CodeBlock language="scala">{`// Mosaik

val mosaikVersion = "0.5.0"
implementation("com.github.MrStahlfelge.mosaik:common-model:$mosaikVersion")
implementation("com.github.MrStahlfelge.mosaik:common-model-ktx:$mosaikVersion")
implementation("com.github.MrStahlfelge.mosaik:serialization-jackson:$mosaikVersion")`}</CodeBlock>
      <p className="text-gray-300 mb-4">We also need to declare another Nexus server that hosts these files. Change the repositories section (it is in the same <b>build.gradle.kts</b> file) like this:</p>
      <CodeBlock language="typescript">{`repositories {

   mavenCentral()
   maven("https://jitpack.io")
}`}</CodeBlock>
      <p className="text-gray-300 mb-4">If you use IntelliJ, it will automatically offer to resync the project. Do it, and it will download everything needed to use Mosaik.</p>
      <p className="text-gray-300 mb-4">Well done! We need one little tweak now. As said before, Spring will automatically serialize objects to JSON. This automated serialization works well in most cases - but for some cases in Mosaik, the default serialization of Jackson, the library used by Spring here, is not what the standard describes and the executing application expects. So we need to tell Spring that some of our Mosaik objects need a different serialization than the default. Configurations like that are done on the Application class, so we change the application class in <b>MosaikappApplication.kt</b> like the following:</p>
      <CodeBlock language="python">{`@SpringBootApplication

class MosaikappApplication {
  @Bean
  @Primary
  fun objectMapper(): ObjectMapper {
     // enables controller methods annotated with @ResponseBody to directly return
     // Mosaik Actions and elements that will get serialized by Spring automatically
     return org.ergoplatform.mosaik.jackson.MosaikSerializer.getMosaikMapper()
  }
}`}</CodeBlock>
      <p className="text-gray-300 mb-4">This overrides the default “object mapper” (a class to map objects to JSON) with the one defined by Mosaik.</p>
      <p className="text-gray-300 mb-4">Our project setup is complete, and we can start implementing a Mosaik app! Do you remember the Mosaik desktop debugging application we compiled and started in Part 1 of the tutorial series? Keep it ready to be used!</p>

      <h3 className="text-xl font-bold text-orange-400 mb-2 mt-8">A first simple screen</h3>
      <p className="text-gray-300 mb-4">Now we want to define the first screen users get presented when they open up our Mosaik app. This phrase already said implicit what has to come before the first screen: we must define the Mosaik app itself.</p>
      <p className="text-gray-300 mb-4">Let's change our getMainPage method to return a Mosaik app:</p>
      <CodeBlock language="typescript">{`@GetMapping("/")

fun getMainPage(): MosaikApp {
   return mosaikApp(
       "First Mosaik App", // app name shown in executors
       1 // the app version
   ) {
       // define the view here
   }
}`}</CodeBlock>
      <p className="text-gray-300 mb-4">mosaikApp() is a method defined in our Mosaik Kotlin DSL. It takes some parameters describing the app and, most importantly, the initial view screen.</p>
      <p className="text-gray-300 mb-4">A view screen consists of multiple view elements, and some layout elements can contain other view elements. Check out the layout elements demo that you’ve started in part 1: You see that the three main group elements are Row, Column, and Box. There’s also Card which is nothing else than a decorated box.</p>
      <p className="text-gray-300 mb-4">You should use one of these group elements as your root view element on a screen. We will use a card here. Inside the card, we define a label with a standard text for a first project.</p>
      <CodeBlock language="typescript">{`return mosaikApp(

   "First Mosaik App", // app name shown in executors
   1 // the app version
) {
   // define the view here
   card {
       label("Hello Ergo world!")
   }
}`}</CodeBlock>
      <p className="text-gray-300 mb-4">Start the Spring Boot server and use the desktop demo application to run your MosaikApp. It will look like this:</p>
      <img src="../../../assets/img/mosaik/tutorial2-3.png" alt="Mosaik simple UI" className="rounded-xl border border-neutral-700 mb-6" />
      <p className="text-gray-300 mb-4">We see the app name, a somehow expected screen content, and we can also see how our viewtree looks like in JSON. Let’s spice this up a lot.</p>
      <CodeBlock language="typescript">{`// define the view here

card {
   column(Padding.DEFAULT) {
       label("Hello Ergo world!", LabelStyle.HEADLINE2)

       box(Padding.HALF_DEFAULT)

       button("Click me") {
           onClickAction(showDialog("You clicked the button."))
       }
   }
}`}</CodeBlock>
      <p className="text-gray-300 mb-4">Running it results in this view, and the button works and presents a message.</p>
      <img src="../../../assets/img/mosaik/tutorial2-4.png" alt="Mosaik UI with button" className="rounded-xl border border-neutral-700 mb-6" />
      <p className="text-gray-300 mb-4">For the first part, we improved the layout by adding padding between the card outline and the card contents. The padding is declared on the new column element, not the card element. This might be surprising for people used to web design as they probably would expect that declaring padding on the card would be the better way to do this. But this would not work here: Paddings in Mosaik are always added on the outer side of the element. If you now think that a better name would be margin because, in web design, spacing on the outer side of an element is called margin, you are not quite right. Unlike web element’s margins and like web element’s paddings, paddings in Mosaik will always add spacing for neighboring elements.</p>
      <p className="text-gray-300 mb-4">The column element lays out its child elements vertically and linearly so that the button is added below the label, which now has a better suiting style.</p>
      <p className="text-gray-300 mb-4">The box element between the label and the button has no content and simply adds spacing between the label and button.</p>
      <p className="text-gray-300 mb-4">On the button, an onClickAction is set and given an action that shows a dialog with a message. This line looks very innocent, but a lot is going on thanks to the Kotlin DSL. If you Ctrl-Click on “showDialog” and follow the code that is revealed, you will see that this expression actually defines the action and gives it a random id (because we did not set an id on our own, but the action needs an id), adds this action to the set of actions defined in our ViewContent (= the whole visible screen) and returns the action. “onClickAction” assigns the id of the action to the view element’s onClickAction property.</p>
      <p className="text-gray-300 mb-4">Although the code looks like regular programming, it is crucial to keep in mind what is going on behind the scenes to make the JSON serialization work. The behavior implies that defining two different actions with the same id will result in the first action being overwritten:</p>
      <CodeBlock language="scala">{`column(Padding.DEFAULT) {

   label("Hello Ergo world!", LabelStyle.HEADLINE2)

   box(Padding.HALF_DEFAULT)

   button("Click me") {
       onClickAction(showDialog("You clicked the button.", "myaction"))
   }

   val clashingAction = reloadApp("myaction")
}`}</CodeBlock>
      <p className="text-gray-300 mb-4">Although the clashingAction does not seem to be used anywhere in the code, it overwrites the dialog action. Since its ID is assigned to the button, the button will now reload the app.</p>
      <p className="text-gray-300 mb-4">You can now play around, adding some other view elements and actions. Take a look at the view elements and actions demo to see what is available and how to add it. In the next part of the tutorial series, we take a closer look at how the screen content can be altered.</p>
      <p className="text-gray-300 mb-4">If you had any problems in creating the code, you will find it <a href="https://github.com/MrStahlfelge/mosaik-tutorial-series/tree/20ed591936a959fd6ab640e6520dc01e6d6c2d66" className="text-cyan-400 hover:underline" target="_blank" rel="noopener noreferrer">here</a>.</p>
    </>
  );
} 
